### ISSUE TITLE
Cannot distribute a table

### ISSUE THREAD

**Issue by rwozniak** [TiesNetwork/ties.db-ui#1]
Hi, via https://uiproto.tiesdb.com I have created:
- a tablespace **user-registry**
- a table **users**

I have added 4 fields to the table **users** and 2 indexes (one primary). Despite that fact I still cannot distribute the table - the **Distribute table** button is disabled and a tooltip about fields and primary index is present.

How can I distribute this table so that I will be able to access it via my TiesDB node?

**Comment by dukei** [comment]
Yes, you can. I can not reproduce disabled Distribute button. On the [table page](https://uiproto.tiesdb.com/0xaccc3eee84f41a073042a82a5a588019114f39bb91b311be142d1f4f3930f818/0xc52cbf697aa8ab7d1d56649a97b8425744615f96fd0c28d7649d7241c3ae2ff7) open table properties (gear icon on the top right) and you will see enabled Distribute button. See the screenshot attached.

![image](https://user-images.githubusercontent.com/1279262/43398816-c89cd9b8-9411-11e8-9669-3abc1054041a.png)

**Comment by rwozniak** [comment]
Hi Dimitri, thanks for a very quick response.
Actually the problem is with the second step of table distribution:
![screen shot 2018-07-30 at 15 35 42](https://user-images.githubusercontent.com/179009/43400543-464ec190-940e-11e8-86f2-5ca4fc3c3600.png)

**Comment by dukei** [comment]
Indeed. Fixed, please, check.

For ranges and replicas you can specify values 1 and 3 respectively. They do not have effect currently but will have in upcoming updates.

**Comment by rwozniak** [comment]
Indeed fixed, thanks again for a quick reaction.

**Comment by RdeWilde** [comment]
Doesn't work for me. Clicking the distribute button does nothing. In the console it shows an error (see below). Doesn't matter what value I use for range (1, 3) or repliceas (1, 3).

```
bluebird.js:1468 Warning: a promise was created in a handler but was not returned from it
    at y (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:721087)
    at i.n._warn (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:725528)
    at Object.v [as checkForgottenReturns] (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:720906)
    at i._settlePromiseFromHandler (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754304)
    at i._settlePromise (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754990)
    at i._settlePromise0 (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:755692)
    at i._settlePromises (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:757062)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:712736
    at MutationObserver.<anonymous> (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:770655)
From previous event:
    at i.p [as _captureStackTrace] (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:720430)
    at i._then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:749780)
    at i.then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:748148)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:431366
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1427372
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:577839
    at fetchTablespaces (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1125917)
    at e.value (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1124589)
    at commitLifeCycles (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:504055)
    at e (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:507632)
    at A (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:513114)
    at _ (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:512815)
    at p (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:511943)
    at d (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:511333)
    at Object.updateContainer (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:515592)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:527047
    at Object.unbatchedUpdates (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:514340)
    at vn (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:527016)
    at Object.render (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:556382)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:461519
2
bluebird.js:1468 Unhandled rejection e: Submit Validation Failed
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1428857
    at o (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:780703)
    at i._settlePromiseFromHandler (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754146)
    at i._settlePromise (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754990)
    at i._settlePromise0 (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:755692)
    at i._settlePromises (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:756951)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:712736
    at MutationObserver.<anonymous> (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:770655)
From previous event:
    at i.p [as _captureStackTrace] (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:720430)
    at i._then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:749780)
    at i.then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:748148)
    at i.caught.i.catch (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:747798)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1428800
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1427381
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:577839
    at dispatch (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:567668)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:449767
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1427372
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:577839
    at handleDistribute (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1301287)
    at A (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1220999)
    at u (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1221535)
    at r.submit (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1204421)
    at Object.u (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:467900)
    at Object.invokeGuardedCallback (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:531792)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:531909)
    at p (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:468825)
    at b (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469293)
    at g (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469450)
    at Array.forEach (<anonymous>)
    at v (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469094)
    at E (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:470135)
    at Hr (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:546018)
    at kt (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:478251)
    at batchedUpdates (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:514219)
    at Q (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:474242)
bluebird.js:1468 Unhandled rejection e: Submit Validation Failed
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1428857
    at o (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:780703)
    at i._settlePromiseFromHandler (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754146)
    at i._settlePromise (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:754990)
    at i._settlePromise0 (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:755692)
    at i._settlePromises (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:756951)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:712736
    at MutationObserver.<anonymous> (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:770655)
From previous event:
    at i.p [as _captureStackTrace] (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:720430)
    at i._then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:749780)
    at i.then (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:748148)
    at i.caught.i.catch (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:747798)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1428800
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1427381
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:577839
    at dispatch (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:567668)
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:449767
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1427372
    at https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:577839
    at handleDistribute (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1301287)
    at A (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1220999)
    at u (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1221535)
    at r.submit (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:1204421)
    at Object.u (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:467900)
    at Object.invokeGuardedCallback (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:531792)
    at Object.invokeGuardedCallbackAndCatchFirstError (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:531909)
    at p (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:468825)
    at b (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469293)
    at g (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469450)
    at Array.forEach (<anonymous>)
    at v (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:469094)
    at E (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:470135)
    at Hr (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:546018)
    at kt (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:478251)
    at batchedUpdates (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:514219)
    at Q (https://uiproto.tiesdb.com/static/js/main.36678a6b.js:1:474242)
```

**Comment by RdeWilde** [comment]
Oh it worked after reloading. Maybe if validation fails once, it doesn't work anymore?
